CREATE TABLE processing_date_locks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    network_id bigint NOT NULL REFERENCES networks(id) ON DELETE RESTRICT,
    process_type varchar(40) NOT NULL,
    processing_date date NOT NULL,
    scope_key varchar(120) NOT NULL DEFAULT 'NETWORK',
    started_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at timestamp with time zone,
    completed_by varchar(255),
    CONSTRAINT processing_date_lock_uq UNIQUE (network_id, process_type, processing_date, scope_key)
);

CREATE INDEX processing_date_locks_network_date_idx
    ON processing_date_locks (network_id, processing_date DESC);

CREATE TABLE accounting_periods (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    network_id bigint NOT NULL REFERENCES networks(id) ON DELETE RESTRICT,
    period_type varchar(20) NOT NULL CHECK (period_type IN ('DAY_END', 'MONTH_END')),
    period_start date NOT NULL,
    period_end date NOT NULL,
    closed_at timestamp with time zone NOT NULL,
    closed_by varchar(255) NOT NULL,
    reopened_at timestamp with time zone,
    reopened_by varchar(255),
    reopen_reason varchar(500),
    CONSTRAINT accounting_period_dates_ck CHECK (period_end >= period_start),
    CONSTRAINT accounting_period_reopen_ck CHECK (
        (reopened_at IS NULL AND reopened_by IS NULL AND reopen_reason IS NULL)
        OR (reopened_at IS NOT NULL AND reopened_by IS NOT NULL AND reopen_reason IS NOT NULL)
    ),
    CONSTRAINT accounting_period_uq UNIQUE (network_id, period_type, period_start, period_end)
);

CREATE INDEX accounting_periods_active_idx
    ON accounting_periods (network_id, period_start, period_end)
    WHERE reopened_at IS NULL;
