ALTER TABLE saving_accounts
    ADD COLUMN interest_basis varchar(40) NOT NULL DEFAULT 'DAILY_PRODUCT',
    ADD COLUMN capitalization_frequency varchar(20) NOT NULL DEFAULT 'MONTHLY',
    ADD COLUMN day_count_convention varchar(20) NOT NULL DEFAULT 'ACTUAL_365',
    ADD CONSTRAINT saving_accounts_interest_basis_ck CHECK (
        interest_basis IN ('MINIMUM_MONTHLY_BALANCE', 'DAILY_PRODUCT', 'AVERAGE_BALANCE')),
    ADD CONSTRAINT saving_accounts_capitalization_ck CHECK (
        capitalization_frequency IN ('DAILY', 'MONTHLY', 'QUARTERLY', 'ANNUALLY')),
    ADD CONSTRAINT saving_accounts_day_count_ck CHECK (
        day_count_convention IN ('ACTUAL_365', 'ACTUAL_366', 'THIRTY_360'));

INSERT INTO accounts (network_id, code, name, type)
SELECT n.id, values.code, values.name, values.type
FROM networks n
CROSS JOIN (VALUES
    ('2000', 'Member Savings', 'LIABILITY'),
    ('5000', 'Interest Expense', 'EXPENSE')
) AS values(code, name, type)
ON CONFLICT (network_id, code) DO UPDATE
SET name = EXCLUDED.name, type = EXCLUDED.type;

CREATE TABLE savings_interest_accruals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    network_id bigint NOT NULL REFERENCES networks(id) ON DELETE RESTRICT,
    saving_account_id bigint NOT NULL REFERENCES saving_accounts(id) ON DELETE RESTRICT,
    member_id bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    accrual_date date NOT NULL,
    interest_basis varchar(40) NOT NULL,
    capitalization_frequency varchar(20) NOT NULL,
    day_count_convention varchar(20) NOT NULL,
    capitalization_period_start date NOT NULL,
    basis_amount numeric(18,2) NOT NULL CHECK (basis_amount >= 0),
    annual_rate numeric(7,4) NOT NULL CHECK (annual_rate >= 0 AND annual_rate <= 100),
    accrued_amount numeric(18,2) NOT NULL CHECK (accrued_amount >= 0),
    journal_entry_id bigint REFERENCES journal_entries(id) ON DELETE RESTRICT,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT savings_interest_accrual_uq UNIQUE (saving_account_id, member_id, accrual_date),
    CONSTRAINT savings_interest_journal_uq UNIQUE (journal_entry_id)
);

CREATE INDEX savings_interest_network_date_idx
    ON savings_interest_accruals (network_id, accrual_date DESC);
CREATE INDEX savings_interest_member_date_idx
    ON savings_interest_accruals (member_id, accrual_date DESC);
