ALTER TABLE loan_packages
    ADD COLUMN max_loan_to_value_percent numeric(5,2) NOT NULL DEFAULT 70.00,
    ADD COLUMN guarantor_exposure_limit numeric(18,2) NOT NULL DEFAULT 1000000.00,
    ADD CONSTRAINT loan_packages_ltv_ck CHECK (
        max_loan_to_value_percent > 0 AND max_loan_to_value_percent <= 100),
    ADD CONSTRAINT loan_packages_guarantor_limit_ck CHECK (guarantor_exposure_limit > 0);

CREATE TABLE loan_collaterals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    network_id bigint NOT NULL REFERENCES networks(id) ON DELETE RESTRICT,
    loan_application_id bigint NOT NULL REFERENCES loan_applications(id) ON DELETE RESTRICT,
    collateral_type varchar(30) NOT NULL,
    valuation numeric(18,2) NOT NULL CHECK (valuation > 0),
    valuer varchar(255) NOT NULL,
    valuation_date date NOT NULL,
    document_reference varchar(500) NOT NULL,
    plot_number varchar(100),
    area varchar(100),
    location varchar(500),
    ownership_document_reference varchar(500),
    status varchar(20) NOT NULL DEFAULT 'PLEDGED',
    released_at timestamp with time zone,
    released_by varchar(255),
    CONSTRAINT loan_collateral_type_ck CHECK (
        collateral_type IN ('LAND', 'BUILDING', 'VEHICLE', 'DEPOSIT', 'EQUIPMENT', 'OTHER')),
    CONSTRAINT loan_collateral_status_ck CHECK (status IN ('PLEDGED', 'RELEASED')),
    CONSTRAINT loan_collateral_land_ck CHECK (collateral_type <> 'LAND' OR (
        plot_number IS NOT NULL AND area IS NOT NULL AND location IS NOT NULL
        AND ownership_document_reference IS NOT NULL))
);

CREATE TABLE loan_guarantors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    network_id bigint NOT NULL REFERENCES networks(id) ON DELETE RESTRICT,
    loan_application_id bigint NOT NULL REFERENCES loan_applications(id) ON DELETE RESTRICT,
    guarantor_id bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    liability_amount numeric(18,2) NOT NULL CHECK (liability_amount > 0),
    consent_reference varchar(500) NOT NULL,
    consented_at timestamp with time zone NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'ACTIVE',
    released_at timestamp with time zone,
    CONSTRAINT loan_guarantor_status_ck CHECK (status IN ('ACTIVE', 'RELEASED')),
    CONSTRAINT loan_guarantor_member_uq UNIQUE (loan_application_id, guarantor_id)
);

CREATE INDEX loan_collateral_network_status_idx ON loan_collaterals (network_id, status);
CREATE INDEX loan_collateral_loan_idx ON loan_collaterals (loan_application_id);
CREATE INDEX loan_guarantor_member_status_idx ON loan_guarantors (guarantor_id, status);
CREATE INDEX loan_guarantor_loan_idx ON loan_guarantors (loan_application_id);
