ALTER TABLE loan_applications
    ADD COLUMN risk_classification varchar(20) NOT NULL DEFAULT 'PASS',
    ADD COLUMN provision_balance numeric(18,2) NOT NULL DEFAULT 0,
    ADD CONSTRAINT loan_risk_classification_ck CHECK (
        risk_classification IN ('PASS', 'WATCHLIST', 'SUBSTANDARD', 'DOUBTFUL', 'LOSS')),
    ADD CONSTRAINT loan_provision_balance_ck CHECK (provision_balance >= 0);

CREATE TABLE loan_risk_settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    network_id bigint NOT NULL REFERENCES networks(id) ON DELETE RESTRICT,
    watchlist_days integer NOT NULL DEFAULT 1,
    substandard_days integer NOT NULL DEFAULT 30,
    doubtful_days integer NOT NULL DEFAULT 90,
    loss_days integer NOT NULL DEFAULT 180,
    pass_rate numeric(5,2) NOT NULL DEFAULT 1.00,
    watchlist_rate numeric(5,2) NOT NULL DEFAULT 5.00,
    substandard_rate numeric(5,2) NOT NULL DEFAULT 25.00,
    doubtful_rate numeric(5,2) NOT NULL DEFAULT 50.00,
    loss_rate numeric(5,2) NOT NULL DEFAULT 100.00,
    CONSTRAINT loan_risk_settings_network_uq UNIQUE (network_id),
    CONSTRAINT loan_risk_thresholds_ck CHECK (
        watchlist_days >= 0 AND watchlist_days < substandard_days
        AND substandard_days < doubtful_days AND doubtful_days < loss_days),
    CONSTRAINT loan_risk_rates_ck CHECK (
        pass_rate BETWEEN 0 AND 100 AND watchlist_rate BETWEEN 0 AND 100
        AND substandard_rate BETWEEN 0 AND 100 AND doubtful_rate BETWEEN 0 AND 100
        AND loss_rate BETWEEN 0 AND 100)
);

CREATE TABLE loan_classifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    network_id bigint NOT NULL REFERENCES networks(id) ON DELETE RESTRICT,
    loan_application_id bigint NOT NULL REFERENCES loan_applications(id) ON DELETE RESTRICT,
    classification_date date NOT NULL,
    oldest_overdue_date date,
    days_past_due integer NOT NULL CHECK (days_past_due >= 0),
    classification varchar(20) NOT NULL,
    outstanding_principal numeric(18,2) NOT NULL CHECK (outstanding_principal >= 0),
    provision_rate numeric(5,2) NOT NULL CHECK (provision_rate BETWEEN 0 AND 100),
    required_provision numeric(18,2) NOT NULL CHECK (required_provision >= 0),
    previous_provision numeric(18,2) NOT NULL CHECK (previous_provision >= 0),
    provision_change numeric(18,2) NOT NULL,
    journal_entry_id bigint REFERENCES journal_entries(id) ON DELETE RESTRICT,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT loan_classification_value_ck CHECK (
        classification IN ('PASS', 'WATCHLIST', 'SUBSTANDARD', 'DOUBTFUL', 'LOSS')),
    CONSTRAINT loan_classification_daily_uq UNIQUE (loan_application_id, classification_date),
    CONSTRAINT loan_classification_journal_uq UNIQUE (journal_entry_id)
);

INSERT INTO accounts (network_id, code, name, type)
SELECT n.id, values.code, values.name, values.type
FROM networks n
CROSS JOIN (VALUES
    ('1190', 'Loan Loss Provision', 'ASSET'),
    ('5200', 'Provision Expense', 'EXPENSE')
) AS values(code, name, type)
ON CONFLICT (network_id, code) DO UPDATE SET name = EXCLUDED.name, type = EXCLUDED.type;

CREATE INDEX loan_classification_network_date_idx ON loan_classifications (network_id, classification_date DESC);
CREATE INDEX loan_classification_loan_date_idx ON loan_classifications (loan_application_id, classification_date DESC);
