CREATE TABLE networks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registered_id varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    address varchar(255),
    created_at varchar(255),
    phone varchar(255),
    pan_number varchar(255),
    staff_count integer NOT NULL DEFAULT 0 CHECK (staff_count >= 0),
    user_count integer NOT NULL DEFAULT 0 CHECK (user_count >= 0),
    package_type varchar(255) NOT NULL,
    package_price double precision NOT NULL DEFAULT 0 CHECK (package_price >= 0),
    document_data bytea,
    document_name varchar(255),
    document_type varchar(255),
    logo_data bytea,
    logo_name varchar(255),
    logo_type varchar(255),
    admin_limit integer CHECK (admin_limit IS NULL OR admin_limit >= 0),
    user_limit integer CHECK (user_limit IS NULL OR user_limit >= 0),
    CONSTRAINT networks_registered_id_uq UNIQUE (registered_id),
    CONSTRAINT networks_name_uq UNIQUE (name),
    CONSTRAINT networks_package_type_ck CHECK (lower(package_type) IN ('basic', 'premium', 'custom'))
);

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    email varchar(255) NOT NULL,
    phone varchar(255),
    role varchar(255) NOT NULL,
    sahakari varchar(255) NOT NULL,
    sahakari_id bigint NOT NULL REFERENCES networks(id) ON DELETE RESTRICT,
    password varchar(255) NOT NULL,
    status varchar(255) NOT NULL DEFAULT 'Pending',
    dob varchar(255),
    address varchar(255),
    balance double precision NOT NULL DEFAULT 0,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    two_factor_code varchar(255),
    two_factor_expiry timestamp without time zone,
    trusted_device_token varchar(255),
    trusted_device_expiry timestamp without time zone,
    photo_data bytea,
    photo_name varchar(255),
    photo_type varchar(255),
    citizenship_data bytea,
    citizenship_name varchar(255),
    citizenship_type varchar(255),
    signature_data bytea,
    signature_name varchar(255),
    signature_type varchar(255),
    CONSTRAINT users_role_ck CHECK (lower(role) IN ('member', 'admin')),
    CONSTRAINT users_status_ck CHECK (status IN ('Pending', 'Active', 'Rejected', 'Suspended')),
    CONSTRAINT users_balance_ck CHECK (balance >= 0)
);

CREATE UNIQUE INDEX users_email_normalized_uq ON users (lower(email));
CREATE INDEX users_sahakari_id_idx ON users (sahakari_id);
CREATE INDEX users_role_status_idx ON users (role, status);

CREATE TABLE fixed_deposits (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    interest_rate double precision NOT NULL CHECK (interest_rate >= 0 AND interest_rate <= 100),
    min_duration integer NOT NULL CHECK (min_duration > 0),
    min_amount double precision NOT NULL CHECK (min_amount > 0),
    description varchar(1000),
    network_id bigint NOT NULL REFERENCES networks(id) ON DELETE CASCADE,
    banner_data bytea,
    banner_name varchar(255),
    banner_type varchar(255),
    CONSTRAINT fixed_deposits_network_name_uq UNIQUE (network_id, name)
);

CREATE TABLE saving_accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    interest_rate double precision NOT NULL CHECK (interest_rate >= 0 AND interest_rate <= 100),
    min_balance double precision NOT NULL CHECK (min_balance >= 0),
    description varchar(1000),
    network_id bigint NOT NULL REFERENCES networks(id) ON DELETE CASCADE,
    banner_data bytea,
    banner_name varchar(255),
    banner_type varchar(255),
    CONSTRAINT saving_accounts_network_name_uq UNIQUE (network_id, name)
);

CREATE TABLE loan_packages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    interest_rate double precision NOT NULL CHECK (interest_rate >= 0 AND interest_rate <= 100),
    max_amount double precision NOT NULL CHECK (max_amount > 0),
    max_duration integer NOT NULL CHECK (max_duration > 0),
    description varchar(1000),
    network_id bigint NOT NULL REFERENCES networks(id) ON DELETE CASCADE,
    banner_data bytea,
    banner_name varchar(255),
    banner_type varchar(255),
    CONSTRAINT loan_packages_network_name_uq UNIQUE (network_id, name)
);

CREATE TABLE fixed_deposit_applications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    fixed_deposit_id bigint NOT NULL REFERENCES fixed_deposits(id) ON DELETE RESTRICT,
    network_id bigint NOT NULL REFERENCES networks(id) ON DELETE RESTRICT,
    deposit_amount double precision NOT NULL CHECK (deposit_amount > 0),
    deposit_term integer NOT NULL CHECK (deposit_term > 0),
    interest_rate double precision CHECK (interest_rate IS NULL OR (interest_rate >= 0 AND interest_rate <= 100)),
    maturity_date date,
    maturity_amount double precision CHECK (maturity_amount IS NULL OR maturity_amount >= 0),
    nominee_name varchar(255),
    status varchar(255) NOT NULL DEFAULT 'PENDING',
    transaction_type varchar(255) NOT NULL DEFAULT 'DEPOSIT',
    application_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    review_date timestamp without time zone,
    reviewed_by bigint REFERENCES users(id) ON DELETE SET NULL,
    review_notes varchar(1000),
    CONSTRAINT fixed_deposit_app_status_ck CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN')),
    CONSTRAINT fixed_deposit_app_type_ck CHECK (transaction_type IN ('DEPOSIT', 'WITHDRAW'))
);

CREATE TABLE saving_account_applications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    saving_account_id bigint NOT NULL REFERENCES saving_accounts(id) ON DELETE RESTRICT,
    network_id bigint NOT NULL REFERENCES networks(id) ON DELETE RESTRICT,
    initial_deposit double precision NOT NULL CHECK (initial_deposit > 0),
    status varchar(255) NOT NULL DEFAULT 'PENDING',
    transaction_type varchar(255) NOT NULL DEFAULT 'DEPOSIT',
    application_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    review_date timestamp without time zone,
    reviewed_by bigint REFERENCES users(id) ON DELETE SET NULL,
    review_notes varchar(1000),
    CONSTRAINT saving_account_app_status_ck CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN')),
    CONSTRAINT saving_account_app_type_ck CHECK (transaction_type IN ('DEPOSIT', 'WITHDRAW'))
);

CREATE TABLE loan_applications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    loan_package_id bigint NOT NULL REFERENCES loan_packages(id) ON DELETE RESTRICT,
    network_id bigint NOT NULL REFERENCES networks(id) ON DELETE RESTRICT,
    requested_amount double precision NOT NULL CHECK (requested_amount > 0),
    approved_amount double precision CHECK (approved_amount IS NULL OR approved_amount > 0),
    interest_rate double precision CHECK (interest_rate IS NULL OR (interest_rate >= 0 AND interest_rate <= 100)),
    duration_in_months integer CHECK (duration_in_months IS NULL OR duration_in_months > 0),
    start_date date,
    next_payment_date date,
    purpose varchar(2000),
    status varchar(255) NOT NULL DEFAULT 'PENDING',
    transaction_type varchar(255) NOT NULL DEFAULT 'WITHDRAW',
    application_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    review_date timestamp without time zone,
    reviewed_by bigint REFERENCES users(id) ON DELETE SET NULL,
    review_notes varchar(1000),
    CONSTRAINT loan_app_status_ck CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN')),
    CONSTRAINT loan_app_type_ck CHECK (transaction_type IN ('DEPOSIT', 'WITHDRAW'))
);

CREATE TABLE repayment_schedules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_application_id bigint NOT NULL REFERENCES loan_applications(id) ON DELETE CASCADE,
    installment_number integer NOT NULL CHECK (installment_number > 0),
    due_date date NOT NULL,
    principal_amount double precision NOT NULL CHECK (principal_amount >= 0),
    interest_amount double precision NOT NULL CHECK (interest_amount >= 0),
    total_due double precision NOT NULL CHECK (total_due > 0),
    status varchar(255) NOT NULL DEFAULT 'PENDING',
    paid_date date,
    CONSTRAINT repayment_schedule_installment_uq UNIQUE (loan_application_id, installment_number),
    CONSTRAINT repayment_schedule_status_ck CHECK (status IN ('PENDING', 'PAID', 'PARTIAL', 'OVERDUE'))
);

CREATE TABLE transactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id varchar(255) NOT NULL,
    date date NOT NULL,
    status varchar(255) NOT NULL,
    user_id bigint REFERENCES users(id) ON DELETE RESTRICT,
    user_name varchar(255),
    network_id bigint NOT NULL REFERENCES networks(id) ON DELETE RESTRICT,
    type varchar(255) NOT NULL,
    amount double precision NOT NULL CHECK (amount > 0),
    narration varchar(1000),
    application_id bigint,
    application_type varchar(255),
    network_reserve double precision,
    mode varchar(255),
    fy_type varchar(255),
    account_head varchar(255),
    network_ledger varchar(255),
    direction varchar(255),
    payment_method varchar(255),
    cheque_no varchar(255),
    bank_name varchar(255),
    received_by varchar(255),
    CONSTRAINT transactions_voucher_id_uq UNIQUE (voucher_id),
    CONSTRAINT transactions_status_ck CHECK (status IN ('Success', 'Frozen', 'Reversed')),
    CONSTRAINT transactions_direction_ck CHECK (direction IS NULL OR direction IN ('Credit', 'Debit')),
    CONSTRAINT transactions_mode_ck CHECK (mode IS NULL OR mode IN ('member', 'network'))
);

CREATE TABLE activity_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_name varchar(255) NOT NULL,
    role varchar(255) NOT NULL,
    sahakari_id bigint REFERENCES networks(id) ON DELETE SET NULL,
    action varchar(255) NOT NULL,
    details varchar(255),
    timestamp timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX fixed_deposits_network_id_idx ON fixed_deposits (network_id);
CREATE INDEX saving_accounts_network_id_idx ON saving_accounts (network_id);
CREATE INDEX loan_packages_network_id_idx ON loan_packages (network_id);
CREATE INDEX fixed_deposit_apps_network_status_idx ON fixed_deposit_applications (network_id, status);
CREATE INDEX fixed_deposit_apps_user_id_idx ON fixed_deposit_applications (user_id);
CREATE INDEX saving_account_apps_network_status_idx ON saving_account_applications (network_id, status);
CREATE INDEX saving_account_apps_user_id_idx ON saving_account_applications (user_id);
CREATE INDEX loan_apps_network_status_idx ON loan_applications (network_id, status);
CREATE INDEX loan_apps_user_id_idx ON loan_applications (user_id);
CREATE INDEX repayment_schedules_due_status_idx ON repayment_schedules (due_date, status);
CREATE INDEX transactions_network_date_idx ON transactions (network_id, date DESC);
CREATE INDEX transactions_user_date_idx ON transactions (user_id, date DESC);
CREATE INDEX transactions_application_idx ON transactions (application_type, application_id);
CREATE INDEX activity_logs_network_timestamp_idx ON activity_logs (sahakari_id, timestamp DESC);
