-- Double-entry ledger: chart of accounts, journal, and the invariants that make it a
-- ledger rather than a log.
--
-- Three properties are enforced here rather than in application code, because application
-- code can be bypassed and a ledger that can be bypassed proves nothing:
--   1. every journal entry balances (deferred constraint trigger, checked at commit),
--   2. posted entries and lines can never be updated or deleted (only reversed),
--   3. each entry carries the hash of the previous entry for its cooperative, so a
--      rewrite anywhere in the chain is detectable.

CREATE TABLE accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    network_id bigint NOT NULL REFERENCES networks(id) ON DELETE CASCADE,
    code varchar(20) NOT NULL,
    name varchar(255) NOT NULL,
    type varchar(20) NOT NULL,
    active boolean NOT NULL DEFAULT true,
    CONSTRAINT accounts_network_code_uq UNIQUE (network_id, code),
    CONSTRAINT accounts_type_ck CHECK (type IN ('ASSET', 'LIABILITY', 'EQUITY', 'INCOME', 'EXPENSE'))
);

CREATE INDEX accounts_network_idx ON accounts (network_id);

CREATE TABLE journal_entries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    network_id bigint NOT NULL REFERENCES networks(id) ON DELETE RESTRICT,
    sequence_no bigint NOT NULL,
    entry_date date NOT NULL,
    narration varchar(1000) NOT NULL,
    voucher_ref varchar(100),
    source_type varchar(50),
    source_id bigint,
    posted_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    posted_by varchar(255),
    reverses_entry_id bigint REFERENCES journal_entries(id) ON DELETE RESTRICT,
    previous_hash varchar(64) NOT NULL,
    entry_hash varchar(64) NOT NULL,
    CONSTRAINT journal_entries_network_sequence_uq UNIQUE (network_id, sequence_no),
    CONSTRAINT journal_entries_network_hash_uq UNIQUE (network_id, entry_hash)
);

CREATE INDEX journal_entries_network_date_idx ON journal_entries (network_id, entry_date);
CREATE INDEX journal_entries_source_idx ON journal_entries (source_type, source_id);

CREATE TABLE journal_lines (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id bigint NOT NULL REFERENCES journal_entries(id) ON DELETE RESTRICT,
    account_id bigint NOT NULL REFERENCES accounts(id) ON DELETE RESTRICT,
    member_id bigint REFERENCES users(id) ON DELETE RESTRICT,
    debit numeric(18,2) NOT NULL DEFAULT 0,
    credit numeric(18,2) NOT NULL DEFAULT 0,
    line_memo varchar(500),
    -- A line is either a debit or a credit, never both, never neither.
    CONSTRAINT journal_lines_signs_ck CHECK (debit >= 0 AND credit >= 0),
    CONSTRAINT journal_lines_single_side_ck CHECK ((debit = 0) <> (credit = 0))
);

CREATE INDEX journal_lines_entry_idx ON journal_lines (entry_id);
CREATE INDEX journal_lines_account_idx ON journal_lines (account_id);
CREATE INDEX journal_lines_member_idx ON journal_lines (member_id);

-- 1. Balanced entries. Deferred to commit so an entry may be built one line at a time.
CREATE FUNCTION journal_entry_must_balance() RETURNS trigger AS $$
DECLARE
    target_entry bigint := COALESCE(NEW.entry_id, OLD.entry_id);
    total_debit numeric(18,2);
    total_credit numeric(18,2);
    line_count integer;
BEGIN
    SELECT COALESCE(SUM(debit), 0), COALESCE(SUM(credit), 0), COUNT(*)
      INTO total_debit, total_credit, line_count
      FROM journal_lines WHERE entry_id = target_entry;

    IF line_count < 2 THEN
        RAISE EXCEPTION 'Journal entry % needs at least two lines, found %', target_entry, line_count;
    END IF;

    IF total_debit <> total_credit THEN
        RAISE EXCEPTION 'Journal entry % is unbalanced: debit % <> credit %',
            target_entry, total_debit, total_credit;
    END IF;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER journal_lines_balance_ck
    AFTER INSERT ON journal_lines
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION journal_entry_must_balance();

-- 2. Append-only. Corrections are reversing entries, never edits.
--    Production should also revoke UPDATE/DELETE on these tables from the runtime role;
--    the trigger holds regardless of which role connects.
CREATE FUNCTION journal_is_append_only() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'The journal is append-only: % on % is not allowed. Post a reversing entry instead.',
        TG_OP, TG_TABLE_NAME;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER journal_entries_append_only
    BEFORE UPDATE OR DELETE ON journal_entries
    FOR EACH ROW EXECUTE FUNCTION journal_is_append_only();

CREATE TRIGGER journal_lines_append_only
    BEFORE UPDATE OR DELETE ON journal_lines
    FOR EACH ROW EXECUTE FUNCTION journal_is_append_only();
