-- Cooperative share capital: configurable rules, current certificates, and an
-- append-only register tied to the general ledger.
CREATE TABLE share_settings (
    network_id bigint PRIMARY KEY REFERENCES networks(id) ON DELETE CASCADE,
    unit_price numeric(18,2) NOT NULL DEFAULT 100.00 CHECK (unit_price > 0),
    minimum_shares integer NOT NULL DEFAULT 10 CHECK (minimum_shares > 0),
    statutory_max_shares integer NOT NULL DEFAULT 1000 CHECK (statutory_max_shares >= minimum_shares)
);

INSERT INTO share_settings (network_id)
SELECT id FROM networks
ON CONFLICT (network_id) DO NOTHING;

-- These codes predate this module, but older cooperatives may never have caused
-- the application-level chart bootstrap to run. Seed them explicitly.
INSERT INTO accounts (network_id, code, name, type)
SELECT n.id, values.code, values.name, 'EQUITY'
FROM networks n
CROSS JOIN (VALUES
    ('3000', 'Share Capital'),
    ('3100', 'Statutory Reserve Fund')
) AS values(code, name)
ON CONFLICT (network_id, code) DO NOTHING;

CREATE TABLE share_certificates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    network_id bigint NOT NULL REFERENCES networks(id) ON DELETE RESTRICT,
    member_id bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    certificate_number varchar(80) NOT NULL,
    shares_held integer NOT NULL CHECK (shares_held >= 0),
    issued_date date NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'REFUNDED')),
    CONSTRAINT share_certificate_member_uq UNIQUE (network_id, member_id),
    CONSTRAINT share_certificate_number_uq UNIQUE (network_id, certificate_number)
);

CREATE INDEX share_certificates_network_idx ON share_certificates (network_id, status);

CREATE TABLE share_transactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    network_id bigint NOT NULL REFERENCES networks(id) ON DELETE RESTRICT,
    request_ref varchar(100) NOT NULL,
    transaction_number varchar(80) NOT NULL,
    transaction_type varchar(30) NOT NULL CHECK (transaction_type IN ('PURCHASE', 'ADDITIONAL_PURCHASE', 'TRANSFER', 'REFUND')),
    from_member_id bigint REFERENCES users(id) ON DELETE RESTRICT,
    to_member_id bigint REFERENCES users(id) ON DELETE RESTRICT,
    share_count integer NOT NULL CHECK (share_count > 0),
    unit_price numeric(18,2) NOT NULL CHECK (unit_price > 0),
    total_amount numeric(18,2) NOT NULL CHECK (total_amount > 0),
    transaction_date date NOT NULL,
    journal_entry_id bigint NOT NULL REFERENCES journal_entries(id) ON DELETE RESTRICT,
    narration varchar(500),
    created_by varchar(255) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT share_transactions_request_uq UNIQUE (network_id, request_ref),
    CONSTRAINT share_transactions_number_uq UNIQUE (network_id, transaction_number),
    CONSTRAINT share_transactions_journal_uq UNIQUE (journal_entry_id),
    CONSTRAINT share_transactions_members_ck CHECK (
        (transaction_type IN ('PURCHASE', 'ADDITIONAL_PURCHASE') AND from_member_id IS NULL AND to_member_id IS NOT NULL)
        OR (transaction_type = 'TRANSFER' AND from_member_id IS NOT NULL AND to_member_id IS NOT NULL AND from_member_id <> to_member_id)
        OR (transaction_type = 'REFUND' AND from_member_id IS NOT NULL AND to_member_id IS NULL)
    )
);

CREATE INDEX share_transactions_network_date_idx ON share_transactions (network_id, transaction_date DESC, id DESC);
CREATE INDEX share_transactions_from_member_idx ON share_transactions (from_member_id);
CREATE INDEX share_transactions_to_member_idx ON share_transactions (to_member_id);

CREATE TRIGGER share_transactions_append_only
    BEFORE UPDATE OR DELETE ON share_transactions
    FOR EACH ROW EXECUTE FUNCTION journal_is_append_only();
